services:
  # 1. FastAPI Mikroservisi
  - type: web
    name: fastapi-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/fastapi/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: DB_HOST
        fromDatabase:
          name: devguard-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: devguard-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: devguard-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: devguard-db
          property: password

  # 2. Django REST Framework Mikroservisi
  - type: web
    name: drf-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/drf/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: DB_HOST
        fromDatabase:
          name: devguard-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: devguard-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: devguard-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: devguard-db
          property: password

  # 3. Telegram Bot Mikroservisi
  - type: web
    name: telegram-bot
    env: docker
    dockerContext: .
    dockerfilePath: ./services/bot/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000

databases:
  # Render PostgreSQL Bazasi
  - name: devguard-db
    plan: free
    databaseName: devshield
    user: ibrohim