services:
  # 1. FastAPI
  - type: web
    name: fastapi-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/fastapi/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: dpg-d9kevhnavr4c73as4spg-a
        fromDatabase:
          name: devguard-db
          property: host
      - key: devshield
        fromDatabase:
          name: devguard-db
          property: database
      - key: ibrohim
        fromDatabase:
          name: devguard-db
          property: user
      - key: IgwSxMLganrQABJ6xvRdVGeChwPAsVbF
        fromDatabase:
          name: devguard-db
          property: password

  # 2. Django REST Framework
  - type: web
    name: drf-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/drf/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: dpg-d9kevhnavr4c73as4spg-a
        fromDatabase:
          name: devguard-db
          property: host
      - key: devshield
        fromDatabase:
          name: devguard-db
          property: database
      - key: ibrohim
        fromDatabase:
          name: devguard-db
          property: user
      - key: IgwSxMLganrQABJ6xvRdVGeChwPAsVbF
        fromDatabase:
          name: devguard-db
          property: password

databases:
  # Render PostgreSQL Bazasi
  - name: devguard-db
    plan: free
    databaseName: devguard_db
    user: devguard_user