services:
  # 1. FastAPI Mikroservisi
  - type: web
    name: fastapi-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/fastapi/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000

  # 2. Django REST Framework Mikroservisi
  - type: web
    name: drf-service
    env: docker
    dockerContext: .
    dockerfilePath: ./services/drf/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000

  # 3. Telegram Bot Mikroservisi (Background Worker)
  - type: worker
    name: telegram-bot
    env: docker
    dockerContext: .
    dockerfilePath: ./services/bot/Dockerfile
    plan: free