# Generated by Django 6.0.7 on 2026-07-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('normal', 'normal')], max_length=25)),
                ('about', models.TextField()),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.webapplications')),
            ],
        ),
    ]
