# Generated by Django 6.0.7 on 2026-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_id',
            field=models.CharField(default='devshield_payment:<function uuid4 at 0x776e83aee140>', max_length=300, unique=True),
        ),
    ]
