# Generated by Django 6.0.7 on 2026-07-14 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_transactionhistory_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.webapplications'),
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result_summary', models.JSONField(default=dict)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='users.webapplications')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
