# Generated by Django 6.0.7 on 2026-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transactionhistory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, default=12345, unique=True),
            preserve_default=False,
        ),
    ]
