# Generated by Django 6.0.7 on 2026-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapplications',
            name='domain',
            field=models.URLField(unique=True),
        ),
    ]
