# Generated by Django 6.0.7 on 2026-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_webapplications_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplications',
            name='is_subdomain',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='result_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webapplications',
            name='domain',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
