# Generated by Django 6.0.7 on 2026-07-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_webapplications_is_subdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='scan_type',
            field=models.CharField(choices=[('Ddos attack', 'Ddos attack'), ('Full scan', 'full scan')], default='Full scan', max_length=200),
            preserve_default=False,
        ),
    ]
