# Generated by Django 6.0.7 on 2026-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_scanhistory_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='task_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
