# server {
#     listen: 80;
#     server_name idev.api.devshield.uz;

#     location api/v1/core{
#         proxy_pass http://drf-service:8000
#     }

#     location api/v1/fast{
#         proxy_pass http://fast-service:8001
#     }
# }